version: "3"
services:
  server:
    build: ./server
    container_name: orl-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${LOGS_PATH}:/logs:ro
    ports:
      - "${PORT}:80"
  logger:
    build: ./logger
    container_name: orl-logger
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${VAR_ORL}:/logger
      - ${LOGS_PATH}:/logs
  bot:
    build: ./bot
    container_name: orl-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${VAR_ORL}:/bot
      - ${LOGS_PATH}:/logs:ro
