version: "3"
services:
  server:
    build: ./server
    container_name: orl-server
    user: "${USER_UID}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${LOGS_PATH}:/logs:ro
  logger:
    build: ./logger
    container_name: orl-logger
    user: "${USER_UID}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${VAR_ORL}:/logger
      - ${LOGS_PATH}:/logs
  frontend:
    image: nginx:latest
    container_name: orl-web-static
    restart: unless-stopped
    volumes:
      - ./package/etc/nginx/sites-enabled/overrustlelogs.net.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./server/assets:/var/overrustlelogs/public/assets/:ro
  cache:
    image: varnish:latest
    container_name: orl-web-cache
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    volumes:
      - ./package/etc/varnish/default.vcl:/etc/varnish/default.vcl:ro
  bot:
    build: ./bot
    container_name: orl-bot
    user: "${USER_UID}"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${VAR_ORL}:/bot
      - ${LOGS_PATH}:/logs:ro
